; LLVM IR generated by LLVMGenerator
target datalayout = "e-m:e-p:32:32:i64:64-n32:64-S128"
target triple   = "wasm32-unknown-unknown"

declare i8*  @malloc(i32)
declare void @printInt(i32)
declare void @printString(i8*)
declare i32  @readInt()

@g_v = global i32 0
@.str.0 = private unnamed_addr constant [11 x i8] c"Final v = \00", align 1



define i32 @main() {
entry:
  %r0 = add i32 0, 2
  %r1 = add i32 0, 10
  %r2 = add i32 0, 11
  %r3 = add i32 %r1, %r2
  %r4 = mul i32 %r0, %r3
  store i32 %r4, i32* @g_v
  %r5 = load i32, i32* @g_v
  %r6 = add i32 0, 2
  %r7 = add i32 0, 3
  %r8 = mul i32 %r6, %r7
  %r9 = add i32 %r5, %r8
  store i32 %r9, i32* @g_v
  %r10 = bitcast [11 x i8]* @.str.0 to i8*
  call void @printString(i8* %r10)
  %r11 = load i32, i32* @g_v
  call void @printInt(i32 %r11)
  ret i32 0
}
