; LLVM IR generated by LLVMGenerator
target datalayout = "e-m:e-p:32:32:i64:64-n32:64-S128"
target triple   = "wasm32-unknown-unknown"

declare i8*  @malloc(i32)
declare void @printInt(i32)
declare void @printString(i8*)
declare i32  @readInt()

@g_widget = global %struct.AlphaWidget* null
@.str.0 = private unnamed_addr constant [23 x i8] c"AlphaWidget activated!\00", align 1

%struct.AlphaWidget = type {  }

define void @AlphaWidget_Init(%struct.AlphaWidget* %this) {
entry:
  ret void
}

define void @AlphaWidget_Activate(%struct.AlphaWidget* %this) {
entry:
  %r6 = bitcast [23 x i8]* @.str.0 to i8*
  call void @printString(i8* %r6)
  ret void
}


define i32 @main() {
entry:
  %r0 = getelementptr %struct.AlphaWidget, %struct.AlphaWidget* null, i32 1
  %r1 = ptrtoint %struct.AlphaWidget* %r0 to i32
  %r2 = call i8* @malloc(i32 %r1)
  %r3 = bitcast i8* %r2 to %struct.AlphaWidget*
  store %struct.AlphaWidget* %r3, %struct.AlphaWidget** @g_widget
  %r4 = load %struct.AlphaWidget*, %struct.AlphaWidget** @g_widget
  call void @AlphaWidget_Init(%struct.AlphaWidget* %r4)
  %r5 = load %struct.AlphaWidget*, %struct.AlphaWidget** @g_widget
  call void @AlphaWidget_Activate(%struct.AlphaWidget* %r5)
  ret i32 0
}
