; LLVM IR generated by LLVMGenerator
target datalayout = "e-m:e-p:32:32:i64:64-n32:64-S128"
target triple   = "wasm32-unknown-unknown"

declare i8*  @malloc(i32)
declare void @printInt(i32)
declare void @printString(i8*)
declare i32  @readInt()

@g_fh = global %struct.FileHandler* null
@.str.0 = private unnamed_addr constant [25 x i8] c"--- FileHandler Demo ---\00", align 1
@.str.1 = private unnamed_addr constant [15 x i8] c"After cleanup:\00", align 1
@.str.2 = private unnamed_addr constant [22 x i8] c"--- Demo Complete ---\00", align 1
@.str.3 = private unnamed_addr constant [26 x i8] c"Reading data from file...\00", align 1
@.str.4 = private unnamed_addr constant [24 x i8] c"Writing data to file...\00", align 1

%struct.FileHandler = type {  }

define void @FileHandler_Init(%struct.FileHandler* %this) {
entry:
  ret void
}

define void @FileHandler_Destroy(%struct.FileHandler* %this) {
entry:
  ret void
}

define void @FileHandler_Read(%struct.FileHandler* %this) {
entry:
  %r12 = bitcast [26 x i8]* @.str.3 to i8*
  call void @printString(i8* %r12)
  ret void
}

define void @FileHandler_Write(%struct.FileHandler* %this) {
entry:
  %r13 = bitcast [24 x i8]* @.str.4 to i8*
  call void @printString(i8* %r13)
  ret void
}


define i32 @main() {
entry:
  %r0 = bitcast [25 x i8]* @.str.0 to i8*
  call void @printString(i8* %r0)
  %r1 = getelementptr %struct.FileHandler, %struct.FileHandler* null, i32 1
  %r2 = ptrtoint %struct.FileHandler* %r1 to i32
  %r3 = call i8* @malloc(i32 %r2)
  %r4 = bitcast i8* %r3 to %struct.FileHandler*
  store %struct.FileHandler* %r4, %struct.FileHandler** @g_fh
  %r5 = load %struct.FileHandler*, %struct.FileHandler** @g_fh
  call void @FileHandler_Init(%struct.FileHandler* %r5)
  %r6 = load %struct.FileHandler*, %struct.FileHandler** @g_fh
  call void @FileHandler_Read(%struct.FileHandler* %r6)
  %r7 = load %struct.FileHandler*, %struct.FileHandler** @g_fh
  call void @FileHandler_Write(%struct.FileHandler* %r7)
  %r8 = load %struct.FileHandler*, %struct.FileHandler** @g_fh
  call void @FileHandler_Destroy(%struct.FileHandler* %r8)
  %r9 = bitcast [15 x i8]* @.str.1 to i8*
  call void @printString(i8* %r9)
  %r10 = load %struct.FileHandler*, %struct.FileHandler** @g_fh
  call void @FileHandler_Read(%struct.FileHandler* %r10)
  %r11 = bitcast [22 x i8]* @.str.2 to i8*
  call void @printString(i8* %r11)
  ret i32 0
}
