; LLVM IR generated by LLVMGenerator
target datalayout = "e-m:e-p:32:32:i64:64-n32:64-S128"
target triple   = "wasm32-unknown-unknown"

declare i8*  @malloc(i32)
declare void @printInt(i32)
declare void @printString(i8*)
declare i32  @readInt()

@g_fm = global %struct.FileManager* null
@.str.0 = private unnamed_addr constant [22 x i8] c"IReader: default read\00", align 1
@.str.1 = private unnamed_addr constant [23 x i8] c"IWriter: default write\00", align 1
@.str.2 = private unnamed_addr constant [36 x i8] c"FileManager: reading data from file\00", align 1
@.str.3 = private unnamed_addr constant [34 x i8] c"FileManager: writing data to file\00", align 1

%struct.IReader = type {  }
%struct.IWriter = type {  }
%struct.FileManager = type {  }

define void @IReader_Init(%struct.IReader* %this) {
entry:
  ret void
}

define void @IReader_Read(%struct.IReader* %this) {
entry:
  %r7 = bitcast [22 x i8]* @.str.0 to i8*
  call void @printString(i8* %r7)
  ret void
}

define void @IWriter_Init(%struct.IWriter* %this) {
entry:
  ret void
}

define void @IWriter_Write(%struct.IWriter* %this) {
entry:
  %r8 = bitcast [23 x i8]* @.str.1 to i8*
  call void @printString(i8* %r8)
  ret void
}

define void @FileManager_Init(%struct.FileManager* %this) {
entry:
  ret void
}

define void @FileManager_Read(%struct.FileManager* %this) {
entry:
  %r9 = bitcast [36 x i8]* @.str.2 to i8*
  call void @printString(i8* %r9)
  ret void
}

define void @FileManager_Write(%struct.FileManager* %this) {
entry:
  %r10 = bitcast [34 x i8]* @.str.3 to i8*
  call void @printString(i8* %r10)
  ret void
}


define i32 @main() {
entry:
  %r0 = getelementptr %struct.FileManager, %struct.FileManager* null, i32 1
  %r1 = ptrtoint %struct.FileManager* %r0 to i32
  %r2 = call i8* @malloc(i32 %r1)
  %r3 = bitcast i8* %r2 to %struct.FileManager*
  store %struct.FileManager* %r3, %struct.FileManager** @g_fm
  %r4 = load %struct.FileManager*, %struct.FileManager** @g_fm
  call void @FileManager_Init(%struct.FileManager* %r4)
  %r5 = load %struct.FileManager*, %struct.FileManager** @g_fm
  call void @FileManager_Read(%struct.FileManager* %r5)
  %r6 = load %struct.FileManager*, %struct.FileManager** @g_fm
  call void @FileManager_Write(%struct.FileManager* %r6)
  ret i32 0
}
