; LLVM IR generated by LLVMGenerator
target datalayout = "e-m:e-p:32:32:i64:64-n32:64-S128"
target triple   = "wasm32-unknown-unknown"

declare i8*  @malloc(i32)
declare void @printInt(i32)
declare void @printString(i8*)
declare i32  @readInt()

@g_fuel = global i32 0
@.str.0 = private unnamed_addr constant [21 x i8] c"Fuel monitor start: \00", align 1
@.str.4 = private unnamed_addr constant [13 x i8] c"Fuel level: \00", align 1
@.str.5 = private unnamed_addr constant [11 x i8] c"Fuel empty\00", align 1



define i32 @main() {
entry:
  %r0 = add i32 0, 5
  store i32 %r0, i32* @g_fuel
  %r1 = bitcast [21 x i8]* @.str.0 to i8*
  call void @printString(i8* %r1)
  %r2 = load i32, i32* @g_fuel
  call void @printInt(i32 %r2)
  br label %whilecond1

whilecond1:
  %r3 = load i32, i32* @g_fuel
  %r4 = add i32 0, 0
  %r5 = icmp sgt i32 %r3, %r4
  %r6 = zext i1 %r5 to i32
  %r7 = icmp ne i32 %r6, 0
  br i1 %r7, label %whilebody2, label %whileend3

whilebody2:
  %r8 = bitcast [13 x i8]* @.str.4 to i8*
  call void @printString(i8* %r8)
  %r9 = load i32, i32* @g_fuel
  call void @printInt(i32 %r9)
  %r10 = load i32, i32* @g_fuel
  %r11 = add i32 0, 1
  %r12 = sub i32 %r10, %r11
  store i32 %r12, i32* @g_fuel
  br label %whilecond1

whileend3:
  %r13 = bitcast [11 x i8]* @.str.5 to i8*
  call void @printString(i8* %r13)
  ret i32 0
}
